# Generated by Django 5.1.7 on 2025-05-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerprofile',
            options={'verbose_name': '农户信息', 'verbose_name_plural': '农户信息列表'},
        ),
        migrations.AlterModelOptions(
            name='touristprofile',
            options={'verbose_name': '游客信息', 'verbose_name_plural': '游客信息列表'},
        ),
    ]
