# Generated by Django 5.1.7 on 2025-04-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemannouncement',
            options={'verbose_name': '系统公告', 'verbose_name_plural': '系统公告列表'},
        ),
        migrations.DeleteModel(
            name='HomePageOrder',
        ),
    ]
