# Generated by Django 5.1.7 on 2025-04-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': '活动', 'verbose_name_plural': '活动列表'},
        ),
        migrations.AlterModelOptions(
            name='activitycategory',
            options={'verbose_name': '活动分类', 'verbose_name_plural': '活动分类列表'},
        ),
        migrations.AlterModelOptions(
            name='activitycheckin',
            options={'verbose_name': '活动打卡', 'verbose_name_plural': '活动打卡记录'},
        ),
        migrations.AlterModelOptions(
            name='activitycomment',
            options={'verbose_name': '活动评论', 'verbose_name_plural': '活动评论列表'},
        ),
        migrations.AlterModelOptions(
            name='activityimage',
            options={'verbose_name': '活动图片', 'verbose_name_plural': '活动图片列表'},
        ),
        migrations.AlterModelOptions(
            name='activitylike',
            options={'verbose_name': '活动点赞', 'verbose_name_plural': '活动点赞列表'},
        ),
        migrations.AlterModelOptions(
            name='activityphoto',
            options={'verbose_name': '活动照片', 'verbose_name_plural': '活动照片列表'},
        ),
        migrations.AlterModelOptions(
            name='activityreview',
            options={'verbose_name': '活动评价', 'verbose_name_plural': '活动评价列表'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '预约', 'verbose_name_plural': '预约列表'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签列表'},
        ),
    ]
