# Generated by Django 5.1.7 on 2025-04-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycomment',
            name='auto_reply',
            field=models.TextField(blank=True, null=True, verbose_name='自动回复'),
        ),
        migrations.AddField(
            model_name='activityreview',
            name='auto_reply',
            field=models.TextField(blank=True, null=True, verbose_name='自动回复'),
        ),
    ]
